journal/urls.py
"""blog_app URL Configuration"""

from django.urls import path
from .views import (
    EntryListView,
    EntryDetailView,
    EntryCreateView,
    EntryUpdateView,
    EntryDeleteView,
    UserEntryListView,
)
from . import views

app_name = 'journal'

urlpatterns = [
    path('', EntryListView.as_view(), name='home'),
    path('user/<str:username>', UserEntryListView.as_view(), name='user-entries'),
    path('entry/<int:pk>/', EntryDetailView.as_view(), name='entry-detail'),
    path('entry/new/', EntryCreateView.as_view(), name='entry-create'),
    path('entry/<int:pk>/update/', EntryUpdateView.as_view(), name='entry-update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry-delete'),
    path('about/', views.about, name='about'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('journal/', include('journal.urls')),
    path('register/', user_views.register, name='register'),
    # path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('projects/<int:pk>', views.ProjectDetailView.as_view(), name='project-detail'),
    path('activity/<int:pk>', views.ActivityRedirectView.as_view(), name='activity-redirect'),
    path('education/', views.ResourceListView.as_view(), name='education'),
    path('resources/<int:pk>', views.ResourceDetailView.as_view(), name='resource-detail'),
    path('gallery/', views.gallery, name='gallery'),
]

portfolio/models.py
# from django.contrib.contenttypes.fields import GenericRelation

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Competency(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Activity(models.Model):
    """A class to represent the details of my daily coding activities."""
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    statuses = [
        ('a', 'active'),
        ('i', 'inactive'),
        ('c', 'completed'),
    ]
    status = models.CharField(max_length=1, choices=statuses, default='i')
    start_date = models.DateField(blank=True, null=True)
    host_url = models.URLField(blank=True)
    repository = models.URLField(blank=True)
    competencies = models.ManyToManyField(Competency)
    languages = models.ManyToManyField(Language)

    # entries = GenericRelation(Entry)

    def __str__(self):
        return self.name

    def display_competencies(self):
        """Create a string for the competencies. This is required in Admin display."""
        return ', '.join(competency.name for competency in self.competencies.all()[:3])
    #
    display_competencies.short_description = 'Competency'

    def display_languages(self):
        """Create a string for the langueages. This is required in Admin display."""
        return ', '.join(language.name for language in self.languages.all()[:3])

    display_languages.short_description = 'Language'

    # class Meta:
    #     ordering = ['name']


class Project(Activity):
    """Represents the details of projects I create."""
    # todo: plan - a list of the steps I've outlined to complete the project
    # todo: status - I could include a "idea" status as by subclassing statuses

    def get_absolute_url(self):
        return reverse('portfolio:project-detail', args=[str(self.id)])


class Resource(Activity):
    """Represents the details of resources I use for learning."""
    types = [
        ('b', 'book'),
        ('e', 'exercises'),
        ('t', 'tutorial'),
    ]
    type = models.CharField(max_length=1, choices=types)

    def get_absolute_url(self):
        return reverse('portfolio:resource-detail', args=[str(self.id)])

portfolio/views.py
from django.shortcuts import render, redirect
from django.views import generic

from .models import Resource, Project, Activity
from journal.models import Entry


def index(request):
    template = 'portfolio/index.html'
    projects = Project.objects.filter(status='c')
    entries = Entry.objects.all().order_by('-date_posted')[:3]
    resources = Resource.objects.filter(status='a')
    context = {
        'title': 'Home',
        'projects': projects,
        'entries': entries,
        'resources': resources,
    }

    return render(request, template, context)


def about(request):
    template = 'portfolio/about.html'

    context = {
        'title': 'About',
        'description': 'This site was created by robbiecares@gmail.com. It will be used to showcase projects he '
                       'develops and to document his progress as he self-studies to become a software developer.'
    }

    return render(request, template, context)


def gallery(request):
    template = 'portfolio/gallery.html'

    context = {
        'title': 'Gallery',
    }

    return render(request, template, context)


class ActivityRedirectView(generic.RedirectView):
    """Redirect a request for an activity to the appropriate detail page of the activity's sub-class
     (i.e. project or resource)."""

    def get_redirect_url(self, *arg, **kwargs):
        act_id = self.kwargs.get('pk')
        for c in Activity.__subclasses__():
            if (act := c.objects.filter(pk=act_id)).exists():
                break
        return act.first().get_absolute_url()


class ProjectListView(generic.ListView):
    model = Project

    def get_context_data(self, *, object_list=None, **kwargs):
        # Call the base implementation first to get the context
        context = super(ProjectListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['title'] = 'Projects'
        return context


class ProjectDetailView(generic.DetailView):
    model = Project

    def get_context_data(self, *, object_list=None, **kwargs):
        # Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        # Create any data and add it to the context
        context['entries'] = self.object.entry_set.all()
        return context


class ResourceListView(generic.ListView):
    model = Resource
    template_name = 'portfolio/education.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        # Call the base implementation first to get the context
        context = super(ResourceListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['title'] = 'Education'
        return context


class ResourceDetailView(generic.DetailView):
    model = Resource

    def get_context_data(self, *, object_list=None, **kwargs):
        # Call the base implementation first to get the context
        context = super().get_context_data(**kwargs)
        # Create any data and add it to the context
        context['entries'] = self.object.entry_set.all()
        return context

portfolio/templates/portfolio/about.html
{% extends "portfolio/base.html" %}
{% block content %}

{% endblock content %}

portfolio/templates/portfolio/activity_detail.html
{% extends "portfolio/base.html" %}
{% block content %}
<section>
    <h1>{{ object.name }}</h1>
    <p><small>Site: <a href="{{ object.host_url }}">{{ object.host_url }}</a></small></p>
    <p><small>Repo: <a href="{{ object.repository }}">{{ object.repository }}</a></small></p>
    <p>{{ object.description }}</p>
    <p>{{ object.type }}</p>
    <h2>Competencies</h2>
    {% for c in object.competencies.all %}
        <span>{{ c.name }},</span>
    {% endfor %}
    <h2>Details</h2>
    <p>Started: {{ object.start_date }}</p>
    <p>Status: {{ object.get_status_display }}</p>
</section>
<br>
<br>
<section>
    <h2>Latest Updates</h2>
    {% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'journal:entry-create' %}">New Entry</a>
    {% endif %}
    {% include 'journal/entries.html' %}
</section>
{% endblock content %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        {% if title %}
            <title>{{ title }} | Rob's site</title>
        {% else %}
            <title>Rob's Site</title>
        {% endif %}
    </head>
    <body>
        <header>COOL GIANT HEADER!
            <nav>
                <ul>
                    <li><a href="{% url 'portfolio:home' %}">Home</a></li>
                    <li><a href="{% url 'portfolio:about' %}">About</a></li>
                    <li><a href="{% url 'portfolio:projects' %}">Projects</a></li>
                    <li><a href="{% url 'portfolio:education' %}">Education</a></li>
                    <li><a href="{% url 'journal:home' %}">Journal</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="nav-item nav-link" href="{% url 'login' %}">Login</a></li>
    <!--                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>-->
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% if title %}
        <h1>{{ title }}</h1>
        {% endif %}
        {% if description %}
        <p>{{ description }}</p>
        {% endif %}
        {% block content %}
        {% endblock content %}
        <footer>
            <a href="mailto: robbiecares@gmail.com" target="_blank">Contact</a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        </footer>
    </body>
</html>

portfolio/templates/portfolio/education.html
{% extends "portfolio/base.html" %}
{% block content %}
<main>
    <section>
        <p>I'm interested in learning Python to help me analyze data and develop websites. I'm currently following the
            "road map" outlined at <a href="https://programmerspyramid.com/">Programmer's Pyramid</a>. Typically, I
            learn/train in the mornings and work on one of my projects in the afternoons.</p>
    </section>
    <section>
        <h2>Learning Resources</h2>
        {% for obj in resource_list %}
            <p><a href="{% url 'portfolio:resource-detail' obj.pk %}">{{ obj.name }}</a></p>
        {% endfor %}
    </section>
</main>
{% endblock content %}

portfolio/templates/portfolio/gallery.html
{% extends "portfolio/base.html" %}
{% block content %}
<main>
<img src="../../media/na_morskie_oko_z_Dori.jpg" alt="na_morskie_oko_z_Dori" width="100%" height="100%">
</main>
{% endblock content %}

portfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %}
{% block content %}
<section class="col-lg-4 col-md-6">
    <div>
        <h2 id="projects">Featured Projects</h2>
        <ul>
        {% for obj in projects %}
            <li><a href="{% url 'portfolio:project-detail' obj.pk %}">{{ obj.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
</section>
<section class="col-lg-4 col-md-6">
    <div>
        <h2 id="learning">Current Learning Resources</h2>
        <ul>
        {% for obj in resources %}
            <li><a href="{% url 'portfolio:resource-detail' obj.pk %}">{{ obj.name }}</a></li>
        {% endfor %}
        </ul>
    </div>
</section>
<section class="col-lg-4 col-md-12">
    <div id='updates'>
        <h2>Latest Updates</h2>
        {% include 'journal/entries.html' %}
    </div>
</section>
{% endblock content %}

portfolio/templates/portfolio/project_detail.html
{% extends "portfolio/project_list.html" %}
{% block content %}
<section>
    <h1>{{ object.name }}</h1>
    {% if object.host_url %}
        <p><small>Site: <a href="{{ object.host_url }}">{{ object.host_url }}</a></small></p>
    {% endif %}
    <p><small>Repo: <a href="{{ object.repository }}">{{ object.repository }}</a></small></p>
    <p>{{ object.description }}</p>
    <p>{{ object.type }}</p>
    <h2>Details</h2>
    <p>Competencies: {{ object.display_competencies }}</p>
    <p>Languages: {{ object.display_languages }}</p>
    <p>Started: {{ object.start_date }}</p>
    <p>Status: {{ object.get_status_display }}</p>
    <p>Project Journal: </p>
</section>
<br>
<br>
<!--    todo: If project status != completed, show lastest updates-->
<section>
    <h2>Latest Updates</h2>
    {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'journal:entry-create' %}">New Entry</a>
    {% endif %}
    {% include 'journal/entries.html' %}
</section>
{% endblock content %}

portfolio/templates/portfolio/project_list.html
{% extends "portfolio/base.html" %}
{% block content %}
<main>
    <section>
    {% for obj in project_list %}
        <p><a href="{% url 'portfolio:project-detail' obj.pk %}">{{ obj.name }}</a>
            {% if obj.host_url %}
                - <a href="{{ obj.host_url }}">url</a>
            {% endif %}
        </p>

    {% endfor %}
    </section>
    <section>
        <p><a href="https://github.com/robbiecares?tab=repositories">My Github repo</a></p>
    </section>
</main>
{% endblock content %}

portfolio/templates/portfolio/resource_detail.html
{% extends "portfolio/education.html" %}
{% block content %}
<section>
    <h1>{{ object.name }}</h1>
    <p><small>Site: <a href="{{ object.host_url }}">{{ object.host_url }}</a></small></p>
    <p><small>Repo: <a href="{{ object.repository }}">{{ object.repository }}</a></small></p>
    <p>{{ object.description }}</p>
    <p>{{ object.type }}</p>
    <h2>Competencies</h2>
    {% for c in object.competencies.all %}
        <span>{{ c.name }},</span>
    {% endfor %}
    <h2>Details</h2>
    <p>Started: {{ object.start_date }}</p>
    <p>Status: {{ object.get_status_display }}</p>
</section>
<br>
<br>
<section>
    <h2>Latest Updates</h2>
    {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'journal:entry-create' %}">New Entry</a>
    {% endif %}
    {% include 'journal/entries.html' %}
</section>
{% endblock content %}

portfolio/templates/portfolio/tutorial_list.html
    {% extends "portfolio/base.html" %}

    {% block content %}
    <main>
        <h1>{{ title }}</h1>
        <section>
            <table>
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Status</td>
<!--                        <td>Completed Units</td>-->
                        <td>Total Units</td>
                    </tr>
                </thead>
                <tbody>
                    {% for tutorial in tutorial_list %}
                    <tr>
                        <td><a href="{% url 'portfolio:tutorial-detail' tutorial.pk %}">{{ tutorial.name }}</a></td>
                        <td>{{ tutorial.get_status_display }}</td>
<!--                        <td>0</td>-->
                        <td>{{ tutorial.units }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>



        </section>
    </main>
    {% endblock content %}