journal/urls.py
"""blog_app URL Configuration"""

from django.urls import path
from .views import (
    EntryListView,
    EntryDetailView,
    EntryCreateView,
    EntryUpdateView,
    EntryDeleteView,
    UserEntryListView,
)
from . import views

app_name = 'journal'

urlpatterns = [
    path('', EntryListView.as_view(), name='home'),
    path('user/<str:username>', UserEntryListView.as_view(), name='user-entries'),
    path('entry/<int:pk>/', EntryDetailView.as_view(), name='entry-detail'),
    path('entry/new/', EntryCreateView.as_view(), name='entry-create'),
    path('entry/<int:pk>/update/', EntryUpdateView.as_view(), name='entry-update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='entry-delete'),
    path('about/', views.about, name='about'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('journal/', include('journal.urls')),
    path('register/', user_views.register, name='register'),
    # path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('projects/<int:pk>', views.ProjectDetailView.as_view(), name='project-detail'),
    path('activity/<int:pk>', views.ActivityRedirectView.as_view(), name='activity-redirect'),
    path('education/', views.ResourceListView.as_view(), name='education'),
    path('resources/<int:pk>', views.ResourceDetailView.as_view(), name='resource-detail'),
    path('gallery/', views.gallery, name='gallery'),
]

journal/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from portfolio.models import Activity, Project


class Entry(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    # todo: what should happen if a user is removed from the system? Set author value to 'deleted' (like Reddit)?
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('journal:entry-detail', kwargs={'pk': self.pk})

journal/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from .models import Entry


# def home(request):
#     template = 'journal/index.html'
#     context = {
#         'entries': Entry.objects.all(),
#     }
#
#     return render(request, template, context)


class EntryListView(ListView):
    model = Entry
    template_name = 'journal/index.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'entries'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Journal'
        return context


class UserEntryListView(ListView):
    model = Entry
    template_name = 'journal/user_entries.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'entries'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Entry.objects.filter(author=user).order_by('-date_posted')


class EntryDetailView(DetailView):
    model = Entry


class EntryCreateView(LoginRequiredMixin, CreateView):
    model = Entry
    template_name = 'journal/entry_form.html'
    context_object_name = 'entry'
    fields = ['title', 'activity', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class EntryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Entry
    fields = ['title', 'activity', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        entry = self.get_object()
        return True if self.request.user == entry.author else False


class EntryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Entry
    success_url = '/'

    def test_func(self):
        entry = self.get_object()
        if self.request.user == entry.author:
            return True
        return False


def about(request):
    template = 'journal/about.html'
    context = {}

    return render(request, template, context)

journal/templates/journal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type='text/css' href="{% static 'journal/main.css' %}">

    {% if title %}
        <title>Rob's Site - { title }</title>
    {% else %}
        <title>Rob's Site</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'journal:home' %}">Rob's Site</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'journal:home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'journal:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'journal:entry-create' %}">New Entry</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
<!--        <div class="col-md-4">-->
<!--          <div class="content-section">-->
<!--            <h3>Our Sidebar</h3>-->
<!--            <p class='text-muted'>You can put any information here you'd like.-->
<!--              <ul class="list-group">-->
<!--                <li class="list-group-item list-group-item-light">Latest Entries</li>-->
<!--                <li class="list-group-item list-group-item-light">Announcements</li>-->
<!--                <li class="list-group-item list-group-item-light">Calendars</li>-->
<!--                <li class="list-group-item list-group-item-light">etc</li>-->
<!--              </ul>-->
<!--            </p>-->
<!--          </div>-->
<!--        </div>-->
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

journal/templates/journal/entries.html
{% block content %}
{% for entry in entries %}
{% load static %}
<!--    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">-->
    <article class="media content-section">
        <img class="rounded-circle article-img" src ="{{ entry.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
<!--                  <a class="mr-2" href="{% url 'journal:user-entries' entry.author.username %}">{{ entry.author }}</a>-->
              <small class="text-muted">{{ entry.date_posted |date:"D, M d, Y"  }}</small>
            </div>
            <h3><a class="article-title" href="{% url 'journal:entry-detail' entry.id %}">{{ entry.title }}</a></h3>
            <p class="article-content">Activity: {{ entry.activity }}</p>
            <p class="article-content">{{ entry.content|truncatewords:30 }}</p>
        </div>
    </article>
{% endfor %}

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page= {{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page= {{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

{% endif %}
{% endblock content %}

journal/templates/journal/entry_confirm_delete.html
{% extends "portfolio/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Entry</legend>
                <h2>Are you sure you want to delete the entry "{{ object.title }}" </h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'journal:entry-detail' object.id %}" >Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

journal/templates/journal/entry_detail.html
{% extends "portfolio/base.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src ="{{ object.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'journal:user-entries' object.author.username %}">{{ entry.author }}</a> -
                <small class="text-muted">{{ object.date_posted |date:"D, M d, Y"  }}</small>
            {% if object.author == user %}
                <br>
                <br>
                <div>
                    <a class='btn btn-secondary btn-sm mt-1 mb-1' href="{% url 'journal:entry-update' object.id %}">Edit</a> -
                    <a class='btn btn-danger btn-sm mt-1 mb-1' href="{% url 'journal:entry-delete' object.id %}">Delete</a>
                </div>
            {% endif %}
            </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">Activity: <a href="{% url 'portfolio:activity-redirect' object.activity.pk %}">{{ object.activity }}</a></p>
        <p class="article-content">{{ object.content }}</p>
        </div>
    </article>
{% endblock content %}

journal/templates/journal/entry_form.html
{% extends "portfolio/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Journal</legend>
                {{ form.as_p }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

journal/templates/journal/index.html
{% extends "portfolio/base.html" %}
{% block content %}
{% if user.is_authenticated %}
    <a class="nav-item nav-link" href="{% url 'journal:entry-create' %}">New Entry</a>
{% endif %}
{% include 'journal/entries.html' %}
{% endblock content %}

journal/templates/journal/user_entries.html
{% extends "journal/base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for entry in entries %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src ="{{ entry.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
                  <small class="text-muted">{{ post.date_posted |date:"D, M d, Y"  }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page= {{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page= {{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}